# Generated by Django 4.0.6 on 2022-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('dat', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('categor', models.CharField(max_length=60, verbose_name='Категории')),
            ],
        ),
    ]
